In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../player_stats.csv')

C:\Users\Praet\AppData\Local\Temp\ipykernel_14672\2275174784.py:1: DtypeWarning: Columns (0: player_id, 1: url) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../player_stats.csv')

In [3]:
df.head(10)

,player_id,version,name,full_name,description,image,height_cm,weight_kg,dob,positions,...,defending_standing_tackle,defending_sliding_tackle,goalkeeping_gk_diving,goalkeeping_gk_handling,goalkeeping_gk_kicking,goalkeeping_gk_positioning,goalkeeping_gk_reflexes,play_styles,url,mentality_attack_position
0,239085,FC 26,E. Haaland,Erling Haaland,"Erling Haaland (Erling Braut Håland, born 21 J...",https://cdn.sofifa.net/players/239/085/26_360.png,195.0,94.0,2000-07-21,ST,...,47,29.0,7.0,14.0,13.0,11.0,7.0,"Low driven shot, Chip shot, Power shot, Precis...",https://sofifa.com/player/239085/erling-haalan...,95.0
1,231747,FC 26,K. Mbappé,Kylian Mbappé,"Kylian Mbappé (Kylian Mbappé Lottin, born 20 D...",https://cdn.sofifa.net/players/231/747/26_360.png,182.0,81.0,1998-12-20,ST,...,34,32.0,13.0,5.0,7.0,11.0,6.0,"Quick step, Finesse shot, Acrobatic, Low drive...",https://sofifa.com/player/231747/kylian-mbappe...,91.0
2,255253,FC 26,Vitinha,Vítor Machado Ferreira,Vitinha (born 13 February 2000) is a Portugues...,https://cdn.sofifa.net/players/255/253/26_360.png,172.0,64.0,2000-02-13,"CM, CDM, CAM",...,79,69.0,12.0,13.0,8.0,5.0,5.0,"Technical, Finesse shot, Incisive pass, Long b...",https://sofifa.com/player/255253/vitor-machado...,81.0
3,252371,FC 26,J. Bellingham,Jude Bellingham,Jude Bellingham (Jude Victor William Bellingha...,https://cdn.sofifa.net/players/252/371/26_360.png,186.0,75.0,2003-06-29,"CAM, CM, LM",...,80,82.0,14.0,11.0,10.0,5.0,8.0,"Relentless, Low driven shot, Gamechanger, Inve...",https://sofifa.com/player/252371/jude-bellingh...,89.0
4,251854,FC 26,Pedri,Pedro González López,Pedri (born 25 November 2002) is a Spanish foo...,https://cdn.sofifa.net/players/251/854/26_360.png,174.0,60.0,2002-11-25,"CM, CDM, CAM",...,85,79.0,12.0,7.0,11.0,8.0,8.0,"First touch, Incisive pass, Long ball pass, Ti...",https://sofifa.com/player/251854/pedro-gonzale...,83.0
5,231443,FC 26,O. Dembélé,Ousmane Dembélé,"Ousmane Dembélé (Masour Ousmane Dembélé, born ...",https://cdn.sofifa.net/players/231/443/26_360.png,178.0,67.0,1997-05-15,"ST, RW, CAM",...,49,39.0,6.0,6.0,14.0,10.0,13.0,"Rapid, Low driven shot, Pinged pass, Inventive...",https://sofifa.com/player/231443/ousmane-dembe...,95.0
6,209331,FC 26,M. Salah,Mohamed Salah,"Mohamed Salah (Mohamed Salah Hamed Ghaly, born...",https://cdn.sofifa.net/players/209/331/26_360.png,175.0,72.0,1992-06-15,"RM, RW",...,43,41.0,14.0,14.0,9.0,11.0,14.0,"Finesse shot, Low driven shot, Gamechanger, Wh...",https://sofifa.com/player/209331/mohamed-salah...,92.0
7,277643,FC 26,Lamine Yamal,Lamine Yamal Nasraoui Ebana,Lamine Yamal (born 13 July 2007) is a Spanish ...,https://cdn.sofifa.net/players/277/643/26_360.png,180.0,72.0,2007-07-13,"RM, RW",...,27,28.0,9.0,13.0,7.0,10.0,7.0,"Technical, Finesse shot, Gamechanger, Incisive...",https://sofifa.com/player/277643/lamine-yamal-...,88.0
8,238794,FC 26,Vini Jr.,Vinícius José de Oliveira Júnior,Vini Jr. (Vinicius José Paixão de Oliveira Jun...,https://cdn.sofifa.net/players/238/794/26_360.png,176.0,73.0,2000-07-12,"LM, ST, LW",...,25,18.0,5.0,7.0,7.0,7.0,10.0,"Quick step, Finesse shot, Chip shot, Gamechang...",https://sofifa.com/player/238794/vinicius-jose...,86.0
9,235212,FC 26,A. Hakimi,Achraf Hakimi,"Achraf Hakimi (Achraf Hakimi Mouh, born 4 Nove...",https://cdn.sofifa.net/players/235/212/26_360.png,181.0,73.0,1998-11-04,"RB, RM",...,85,79.0,10.0,8.0,14.0,6.0,8.0,"Relentless, Low driven shot, Whipped pass, Joc...",https://sofifa.com/player/235212/achraf-hakimi...,84.0

In [4]:
cols_to_drop = [
    'player_id', 
    'version', 
    'description', 
    'image', 
    'international_reputation', 
    'body_type',
    'real_face',
    'specialities',
    'club_id',
    'club_league_id',
    'club_logo',
    'club_rating',
    'club_kit_number',
    'club_joined',
    'country_id',
    'country_league_id',
    'country_league_name',
    'country_flag',
    'country_rating',
    'country_position',
    'country_kit_number',
    'play_styles',
    'url'
    ]

df.drop(columns=cols_to_drop, inplace=True)
df.head(10)

,name,full_name,height_cm,weight_kg,dob,positions,overall_rating,potential,value,wage,...,mentality_composure,defending_defensive_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_gk_diving,goalkeeping_gk_handling,goalkeeping_gk_kicking,goalkeeping_gk_positioning,goalkeeping_gk_reflexes,mentality_attack_position
0,E. Haaland,Erling Haaland,195.0,94.0,2000-07-21,ST,91.0,93.0,172500000.0,390000.0,...,86.0,42,47,29.0,7.0,14.0,13.0,11.0,7.0,95.0
1,K. Mbappé,Kylian Mbappé,182.0,81.0,1998-12-20,ST,91.0,92.0,157000000.0,610000.0,...,88.0,26,34,32.0,13.0,5.0,7.0,11.0,6.0,91.0
2,Vitinha,Vítor Machado Ferreira,172.0,64.0,2000-02-13,"CM, CDM, CAM",90.0,92.0,149000000.0,185000.0,...,88.0,74,79,69.0,12.0,13.0,8.0,5.0,5.0,81.0
3,J. Bellingham,Jude Bellingham,186.0,75.0,2003-06-29,"CAM, CM, LM",90.0,94.0,174500000.0,320000.0,...,90.0,77,80,82.0,14.0,11.0,10.0,5.0,8.0,89.0
4,Pedri,Pedro González López,174.0,60.0,2002-11-25,"CM, CDM, CAM",90.0,93.0,165000000.0,180000.0,...,92.0,74,85,79.0,12.0,7.0,11.0,8.0,8.0,83.0
5,O. Dembélé,Ousmane Dembélé,178.0,67.0,1997-05-15,"ST, RW, CAM",90.0,90.0,122500000.0,220000.0,...,88.0,49,49,39.0,6.0,6.0,14.0,10.0,13.0,95.0
6,M. Salah,Mohamed Salah,175.0,72.0,1992-06-15,"RM, RW",90.0,90.0,74500000.0,240000.0,...,91.0,38,43,41.0,14.0,14.0,9.0,11.0,14.0,92.0
7,Lamine Yamal,Lamine Yamal Nasraoui Ebana,180.0,72.0,2007-07-13,"RM, RW",89.0,95.0,147000000.0,100000.0,...,84.0,23,27,28.0,9.0,13.0,7.0,10.0,7.0,88.0
8,Vini Jr.,Vinícius José de Oliveira Júnior,176.0,73.0,2000-07-12,"LM, ST, LW",89.0,92.0,141000000.0,290000.0,...,83.0,32,25,18.0,5.0,7.0,7.0,7.0,10.0,86.0
9,A. Hakimi,Achraf Hakimi,181.0,73.0,1998-11-04,"RB, RM",89.0,90.0,111000000.0,170000.0,...,84.0,82,85,79.0,10.0,8.0,14.0,6.0,8.0,84.0

In [5]:
#Drop rows with missing country_name or release_clause
df.dropna(subset=['country_name', 'release_clause'], inplace=True)

#Convert all numeric columns to doubles
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[numeric_cols] = df[numeric_cols].astype('float64')

#Convert defending_defensive_awareness, defending_standing_tackle to numeric doubles safely
df['defending_defensive_awareness'] = pd.to_numeric(df['defending_defensive_awareness'], errors='coerce').astype('float64')
df['defending_standing_tackle'] = pd.to_numeric(df['defending_standing_tackle'], errors='coerce').astype('float64')

#convert dob and club_contract_valid_until to datetime
df['dob'] = pd.to_datetime(df['dob'], errors='coerce')
df['club_contract_valid_until'] = pd.to_datetime(df['club_contract_valid_until'], errors='coerce')

#Change preferred_foot to binary
df['preferred_foot'] = df['preferred_foot'].map({'Left': 0, 'Right': 1})

df.head(10)

,name,full_name,height_cm,weight_kg,dob,positions,overall_rating,potential,value,wage,...,mentality_composure,defending_defensive_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_gk_diving,goalkeeping_gk_handling,goalkeeping_gk_kicking,goalkeeping_gk_positioning,goalkeeping_gk_reflexes,mentality_attack_position
0,E. Haaland,Erling Haaland,195.0,94.0,2000-07-21,ST,91.0,93.0,172500000.0,390000.0,...,86.0,42.0,47.0,29.0,7.0,14.0,13.0,11.0,7.0,95.0
1,K. Mbappé,Kylian Mbappé,182.0,81.0,1998-12-20,ST,91.0,92.0,157000000.0,610000.0,...,88.0,26.0,34.0,32.0,13.0,5.0,7.0,11.0,6.0,91.0
2,Vitinha,Vítor Machado Ferreira,172.0,64.0,2000-02-13,"CM, CDM, CAM",90.0,92.0,149000000.0,185000.0,...,88.0,74.0,79.0,69.0,12.0,13.0,8.0,5.0,5.0,81.0
3,J. Bellingham,Jude Bellingham,186.0,75.0,2003-06-29,"CAM, CM, LM",90.0,94.0,174500000.0,320000.0,...,90.0,77.0,80.0,82.0,14.0,11.0,10.0,5.0,8.0,89.0
4,Pedri,Pedro González López,174.0,60.0,2002-11-25,"CM, CDM, CAM",90.0,93.0,165000000.0,180000.0,...,92.0,74.0,85.0,79.0,12.0,7.0,11.0,8.0,8.0,83.0
5,O. Dembélé,Ousmane Dembélé,178.0,67.0,1997-05-15,"ST, RW, CAM",90.0,90.0,122500000.0,220000.0,...,88.0,49.0,49.0,39.0,6.0,6.0,14.0,10.0,13.0,95.0
7,Lamine Yamal,Lamine Yamal Nasraoui Ebana,180.0,72.0,2007-07-13,"RM, RW",89.0,95.0,147000000.0,100000.0,...,84.0,23.0,27.0,28.0,9.0,13.0,7.0,10.0,7.0,88.0
9,A. Hakimi,Achraf Hakimi,181.0,73.0,1998-11-04,"RB, RM",89.0,90.0,111000000.0,170000.0,...,84.0,82.0,85.0,79.0,10.0,8.0,14.0,6.0,8.0,84.0
12,Rodri,Rodrigo Hernández Cascante,190.0,82.0,1996-06-22,"CDM, CM",89.0,89.0,88000000.0,250000.0,...,92.0,88.0,87.0,82.0,10.0,10.0,7.0,14.0,8.0,76.0
13,G. Donnarumma,Gianluigi Donnarumma,196.0,90.0,1999-02-25,GK,89.0,91.0,97000000.0,150000.0,...,54.0,21.0,14.0,16.0,90.0,83.0,72.0,87.0,90.0,14.0

In [6]:
df.to_csv('../player_stats_cleaned.csv', index=False)